Replace dotenv variables with config.json
ethangodt/lit-pics pull request #2
Opened 2018-01-26 00:35 UTC by webbhead777

This replaces functionality previously pointed at dotenv with a config.json file

2018-01-26 00:46 UTC, webbhead777 commented
port: 2287 is "cats" on the num-pad

2018-01-26 00:46 UTC, ethangodt requested changes
👍 at least we gotta change the time thing if it’s not supported.

2018-01-26 00:46 UTC, ethangodt commented on config.template.json
> +        "sid": "xyz",
Is “sid” only for the account? I thought there was message “sid” too? Prefer accountSid or something.

2018-01-26 00:46 UTC, ethangodt commented on config.template.json
> +        "alertTime": "7:00pm",
We don’t actually support this do we? We need to convert this time to a JS date object or cron format.

2018-01-26 00:48 UTC, ethangodt commented
Also your syntax PR is showing up in he list too.

2018-01-26 02:38 UTC, webbhead777 commented on index.js
> +    const splitUrl = MediaUrl0.split('/')
unfortunately this is the only way to pull out the MediaSid property; look at the return object from Twilio if you don't believe me :)

2018-01-26 02:38 UTC, webbhead777 commented on index.js
> +    const MediaSid = splitUrl.find((string) => string.includes('ME'))
unfortunately this is the only way to pull out the MediaSid property; look at the return object from Twilio if you don't believe me :)

2018-01-26 02:44 UTC, webbhead777 commented on index.js
> +        await setTimeout(() => {deleteImage(MessageSid, MediaSid)}, 10000)
I could do this with promises but idk how async/await handles this

2018-01-26 06:12 UTC, ethangodt submitted a review, later dismissed
You can not fix `karma.js` file if you want.

2018-01-26 06:12 UTC, ethangodt commented on README.md
> +        "karma": 0
I'll probably change this but it's fine for now

2018-01-26 06:12 UTC, ethangodt commented on config.template.json
> +        "alertTime": "0 19 * * *",
we should do this more friendly at some point

2018-01-26 06:12 UTC, ethangodt commented on index.js
> +        await setTimeout(() => {deleteImage(MessageSid, MediaSid)}, 10000)
you don't need await here. it's not a promise function. also you can ditch the `{}`

2018-01-26 06:12 UTC, ethangodt commented on lib/karma.js
> +    console.log(JSON.stringify(config))
remove log

2018-01-26 06:12 UTC, ethangodt commented on lib/karma.js
> +module.exports.increment = function increment(name) {
This code is a bit tricky. I'd prefer:
`const updatedParticipant = { ...participant, karma: participant.karma + 1 }`
then save that. I think in general we should just pass around the whole `participant` object instead of passing by name then looking it up later.

Don't change. We're not using this yet. We can change later.

2018-01-26 06:12 UTC, ethangodt commented on lib/karma.js
> +    fs.writeFile('./config.json', JSON.stringify(config, null, 2), function(err) {
We should use promises everywhere so we can `async/await`. If necessary we can `promisify` this. https://www.npmjs.com/package/es6-promisify

2018-01-26 06:12 UTC, ethangodt commented on lib/karma.js
> +const fs = require('fs')
we should just make a participant file and add all the utils and stuff there instead of a karma file

2018-01-26 06:12 UTC, ethangodt commented on lib/messenger.js
> +    return client.messages(messageSid).media(mediaSid)
we should just
1. `return client.messages(messageSid).media(mediaSid).remove()`
2. remove `async`
3. then because it returns promise we can `await` it anywhere else

2018-01-26 06:12 UTC, ethangodt commented on package.json
> +    "dev": "nodemon --inspect . --ignore ./config.json"
👍 (if this list grows we can make a .nodemonignore)

2018-01-27 04:34 UTC, ethangodt commented on index.js
> +        await setTimeout(() => {deleteImage(MessageSid, MediaSid)}, 10000)
do this

2018-01-27 04:35 UTC, ethangodt commented on lib/karma.js
> +    console.log(JSON.stringify(config))
do this

2018-01-27 04:35 UTC, ethangodt commented on lib/karma.js
> +    fs.writeFile('./config.json', JSON.stringify(config, null, 2), function(err) {
do this

2018-01-27 04:35 UTC, ethangodt commented on lib/messenger.js
> +    return client.messages(messageSid).media(mediaSid)
do this

2018-01-27 04:44 UTC, merged